use 5.010;
use strict;
use warnings;

my $filename = 'report.txt';
open(my $fh, '>', $filename) or die "Could not open file '$filename' $!";
say $fh "My first report generated by perl";
close $fh;
say 'done';
